# Generated by Django 3.2.5 on 2021-08-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_auto_20210518_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='backorder_quantity_global_threshold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productvariantchannellisting',
            name='backorder_quantity_threshold',
            field=models.IntegerField(null=True),
        ),
    ]
