# Generated by Django 3.2.6 on 2021-12-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_auto_20210809_2008'),
        ('product', '0150_collection_collection_search_gin'),
    ]

    operations = [
    ]
