# Generated by Django 3.2.6 on 2021-12-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_productchannellisting_product_pro_discoun_3145f3_btree'),
        ('product', '0152_auto_20211206_1848'),
    ]

    operations = [
    ]
