# Generated by Django 3.2.5 on 2021-08-09 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0112_auto_20210616_0548'),
        ('product', '0147_auto_20210809_2008'),
        ('warehouse', '0014_remove_warehouse_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backorder', to='order.orderline')),
                ('product_variant_channel_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='product.productvariantchannellisting')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
