# Generated by Django 3.2.6 on 2021-12-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_stock_quantity'),
        ('warehouse', '0015_backorder'),
    ]

    operations = [
    ]
