# Generated by Django 3.2.12 on 2022-02-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_merge_0015_alter_stock_quantity_0015_backorder'),
        ('warehouse', '0016_stock_quantity_allocated'),
    ]

    operations = [
    ]
