# Generated by Django 3.1.5 on 2021-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneuserprofile',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
