# Generated by Django 3.1.2 on 2021-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_auto_20210316_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneuserprofile',
            name='id_phone_number',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
