# Generated by Django 3.2.6 on 2021-10-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_droneuserprofile_id_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneuserprofile',
            name='dealer_id',
            field=models.IntegerField(null=True),
        ),
    ]
