# Generated by Django 3.2.6 on 2021-10-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_alter_droneuserprofile_dealer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneuserprofile',
            name='is_company_owner',
            field=models.BooleanField(default=False),
        ),
    ]
