# Generated by Django 3.2.5 on 2021-08-05 17:56

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoiceevent_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_json',
            field=models.JSONField(blank=True, db_index=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder),
        ),
    ]
