# Generated by Django 3.1.7 on 2021-04-20 23:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0049_user_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_is_active', models.BooleanField(default=True)),
                ('account_purchasing_restricted', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('company_url', models.CharField(blank=True, max_length=256)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_type', models.CharField(blank=True, max_length=256)),
                ('debit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inside_sales_rep', models.CharField(blank=True, max_length=256)),
                ('internal_ft_notes', models.CharField(blank=True, max_length=256)),
                ('outside_sales_rep', models.CharField(blank=True, max_length=256)),
                ('outside_sales_rep_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('payment_terms', models.CharField(blank=True, max_length=256)),
                ('pricing_list', models.CharField(blank=True, choices=[('MSRP', 'MSRP'), ('dealer', 'Dealer'), ('preferred', 'Preferred'), ('preferred_plus', 'Preferred Plus'), ('elite', 'Elite'), ('distributor', 'Distributor'), ('strategic_partner', 'Strategic Partner'), ('car_dealer_direct', 'Car Dealer Direct'), ('mesa_gold', 'Mesa Gold'), ('mesa_platinum', 'Mesa Platinum'), ('rpm_dealer', 'RPM Dealer'), ('rpm_program', 'RPM Program'), ('rpm_distributor', 'RPM Distributor'), ('rpm_mesa_gold', 'RPM Mesa Gold'), ('rpm_mesa_platinum', 'RPM Mesa Platinum'), ('rpm_strategic_partner', 'RPM Strategic Partner'), ('segi_warranty', 'Segi Warranty'), ('special_pricing', 'Special Pricing')], max_length=50)),
                ('sales_manager', models.CharField(blank=True, max_length=256)),
                ('sap_bp_code', models.CharField(blank=True, max_length=256)),
                ('shipping_preference', models.CharField(blank=True, max_length=256)),
                ('sync_partner', models.BooleanField(default=True)),
                ('warranty_preference', models.CharField(blank=True, max_length=256)),
                ('addresses', models.ManyToManyField(blank=True, related_name='business_partner_addresses', to='account.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SAPUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('is_company_owner', models.BooleanField(default=False)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_partner', to='SAP.businesspartner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.BooleanField(default=True)),
                ('tesa', models.BooleanField(default=True)),
                ('idatalink', models.BooleanField(default=True)),
                ('maestro', models.BooleanField(default=True)),
                ('compustar', models.BooleanField(default=False)),
                ('compustar_pro', models.BooleanField(default=False)),
                ('ftx', models.BooleanField(default=False)),
                ('arctic_start', models.BooleanField(default=False)),
                ('compustar_mesa_only', models.BooleanField(default=False)),
                ('replacements', models.BooleanField(default=True)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAP.businesspartner')),
            ],
        ),
    ]
