# Generated by Django 3.1.7 on 2021-04-21 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='company_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='customer_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='debit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='inside_sales_rep',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='internal_ft_notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='outside_sales_rep',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='outside_sales_rep_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='pricing_list',
            field=models.CharField(blank=True, choices=[('MSRP', 'MSRP'), ('dealer', 'Dealer'), ('preferred', 'Preferred'), ('preferred_plus', 'Preferred Plus'), ('elite', 'Elite'), ('distributor', 'Distributor'), ('strategic_partner', 'Strategic Partner'), ('car_dealer_direct', 'Car Dealer Direct'), ('mesa_gold', 'Mesa Gold'), ('mesa_platinum', 'Mesa Platinum'), ('rpm_dealer', 'RPM Dealer'), ('rpm_program', 'RPM Program'), ('rpm_distributor', 'RPM Distributor'), ('rpm_mesa_gold', 'RPM Mesa Gold'), ('rpm_mesa_platinum', 'RPM Mesa Platinum'), ('rpm_strategic_partner', 'RPM Strategic Partner'), ('segi_warranty', 'Segi Warranty'), ('special_pricing', 'Special Pricing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='sales_manager',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='sap_bp_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='shipping_preference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='warranty_preference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sapuserprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
