# Generated by Django 3.1.7 on 2021-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0002_auto_20210421_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='card_code',
            field=models.CharField(default='default', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='debit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
