# Generated by Django 3.1.7 on 2021-04-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0004_auto_20210427_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapuserprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
