# Generated by Django 3.1.7 on 2021-04-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('SAP', '0005_sapuserprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='pricing_list',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='sapuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
