# Generated by Django 3.1.7 on 2021-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0006_auto_20210429_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='internal_ft_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
