# Generated by Django 3.1.7 on 2021-05-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0007_auto_20210504_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneRewardsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.BooleanField(default=False)),
                ('onboarded', models.BooleanField(default=False)),
                ('distribution', models.CharField(choices=[('stripe', 'Stripe'), ('SAP', 'SAP')], default='stripe', max_length=20)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAP.businesspartner')),
            ],
        ),
    ]
