# Generated by Django 3.1.7 on 2021-05-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0008_dronerewardsprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='card_code',
        ),
    ]
