# Generated by Django 3.1.7 on 2021-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0009_remove_businesspartner_card_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='sap_bp_code',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
