# Generated by Django 3.1.7 on 2021-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0011_auto_20210527_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapuserprofile',
            name='business_partner',
        ),
        migrations.AddField(
            model_name='sapuserprofile',
            name='business_partner',
            field=models.ManyToManyField(blank=True, related_name='business_partner', to='SAP.BusinessPartner'),
        ),
    ]
