# Generated by Django 3.1.7 on 2021-06-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0012_auto_20210603_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapuserprofile',
            name='business_partner',
        ),
        migrations.AddField(
            model_name='sapuserprofile',
            name='business_partners',
            field=models.ManyToManyField(blank=True, related_name='sapuserprofiles', to='SAP.BusinessPartner'),
        ),
    ]
