# Generated by Django 3.2.5 on 2021-08-17 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SAP", "0013_auto_20210603_2139"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesspartner",
            name="outside_sales_rep_emails",
        ),
        migrations.AddField(
            model_name="sapuserprofile",
            name="is_inside_sales_rep",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(model_name="businesspartner", name="inside_sales_rep"),
        migrations.AddField(
            model_name="businesspartner",
            name="inside_sales_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="businesspartner",
            name="outside_sales_rep",
        ),
        migrations.CreateModel(
            name="OutsideSalesRep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "business_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAP.businesspartner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="businesspartner",
            name="outside_sales_rep",
            field=models.ManyToManyField(
                blank=True,
                related_name="outside_sales_reps",
                through="SAP.OutsideSalesRep",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
