# Generated by Django 3.2.5 on 2021-08-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAP', '0014_auto_20210817_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesspartner",
            name="sales_manager",
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='sales_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
