# Generated by Django 3.2.6 on 2021-08-31 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0113_orderevent_app'),
        ('product', '0146_auto_20210518_0945'),
        ('SAP', '0015_alter_businesspartner_sales_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.IntegerField(unique=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=255, null=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAP.businesspartner')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='SAPReturnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
                ('unit_price_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant')),
                ('sap_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='SAP.sapreturn')),
            ],
        ),
    ]
