# Generated by Django 3.2.6 on 2021-09-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0021_alter_sapsalesmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapuserprofile',
            name='business_partners',
        ),
        migrations.RemoveField(
            model_name='sapuserprofile',
            name='is_company_owner',
        ),
    ]
