# Generated by Django 3.2.6 on 2021-09-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0021_alter_sapsalesmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='shipping_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
