# Generated by Django 3.2.6 on 2021-09-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0022_auto_20210928_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPBusinessPartnerMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_owner', models.BooleanField(default=False)),
                ('is_installer', models.BooleanField(default=False)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAP.businesspartner')),
                ('sap_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAP.sapuserprofile')),
            ],
        ),
        migrations.AddField(
            model_name='sapuserprofile',
            name='business_partners',
            field=models.ManyToManyField(blank=True, related_name='sapuserprofiles', through='SAP.SAPBusinessPartnerMembership', to='SAP.BusinessPartner'),
        ),
    ]
