# Generated by Django 3.2.6 on 2021-11-19 18:19

from django.db import migrations

from firstech.SAP.constants import CUSTOM_SAP_SHIPPING_TYPE_NAME
from saleor.shipping import ShippingMethodType


def create_dummy_shipping_method(apps, schema_editor):
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    ShippingMethod = apps.get_model("shipping", "ShippingMethod")
    for zone_id in ShippingZone.objects.values_list("id", flat=True):
        ShippingMethod.objects.create(
            name=CUSTOM_SAP_SHIPPING_TYPE_NAME,
            minimum_order_weight=0,
            type=ShippingMethodType.PRICE_BASED,
            shipping_zone_id=zone_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0022_auto_20211027_2357'),
    ]

    operations = [
        migrations.RunPython(create_dummy_shipping_method)
    ]
