# Generated by Django 3.2.6 on 2021-11-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_merge_20210903_0640'),
        ('SAP', '0023_create_dummy_shipping_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sapreturn',
            old_name='purchase_order',
            new_name='po_number',
        ),
        migrations.RenameField(
            model_name='sapreturn',
            old_name='create_date',
            new_name='sap_create_date',
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='billing_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='customer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='return_type',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('credit', 'Credit'), ('advance', 'Advance'), ('special', 'Special')], default='exchange', max_length=32),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='rma_base',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='rma_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='shipping_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='shipping_method_name',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sapreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='sapreturn',
            name='doc_entry',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
