# Generated by Django 3.2.6 on 2021-10-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0026_alter_sapuserprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapuserprofile',
            options={'permissions': (('drone_activation', 'Can activate drone.'), ('view_wiring', 'Can view wiring diagrams.'), ('view_documents', 'Can view documents.'), ('view_drone_rewards', 'Can view Drone dealer rewards.'), ('view_profile', 'Can view SAP user profile.'), ('purchase_products_b2b', 'Can purchase B2B products.'), ('view_account_balance', 'Can view business partner account balance.'), ('manage_reporting', 'Can create reports.'), ('invite_installers', 'Can invite new installers to business partner.'), ('manage_drone_billing_methods', 'Can manage drone billing methods.'), ('manage_linked_installers', 'Can modify linked installers.'), ('manage_contract', 'Can manage contract.'), ('access_linked_accounts', 'Can view linked accounts.'), ('view_backorders', 'Can view backorders.'), ('place_orders_for_linked_accounts', 'Can place orders for linked accounts.'), ('manage_business_partner_orders', 'Can manage orders for business partner.'), ('define_payments_methods', 'Can define new payment methods.'), ('define_brand_access', 'Can define brand access.'), ('place_orders_for_dealer', 'Can place orders for a dealer.'), ('manage_backorders', 'Can manage backorders.'), ('manage_volume_incentive_rebates', 'Can manage volume incentive rebates.'), ('define_dealer_roles', 'Can define dealer roles.'), ('disable_dealer_account', 'Can disable dealer accounts.'), ('create_past_due_notice', 'Can generate past due notices.'), ('manage_account_statements', 'Can manage account statements.'), ('inside_sales_rep_view', 'Can view business partners as an inside sales rep (all fields).'))},
        ),
    ]
